In [15]:
import json
import pandas as pd
import isodate
import json

In [16]:
with open("data/YT_data_2026-04-27.json", "r", encoding="utf-8") as f:
    data = json.load(f)

In [19]:
print(type(data))

<class 'list'>

In [4]:
df = pd.DataFrame(data)

In [5]:
df

,videoId,title,publishedAt,duration,viewCount,likeCount,commentCount
0,SooHwC2S1iI,▶️ [REPLAY] - La carte de l'IA | Partie 2,2024-10-06T19:13:49Z,PT1H17M50S,29566,1171,65
1,mT6NnslbNLM,▶️ [REPLAY] - La carte de l'IA | Partie 1,2024-10-04T18:19:29Z,PT1H8M32S,52922,2726,192
2,SgPQe2orwAk,JE SUIS DE RETOUR ! 🚀 (et j'ai une surprise po...,2024-08-22T08:23:28Z,PT3M13S,40507,3753,663
3,Je4TH0wpgQc,Comment Développer une IA capable de créer des...,2022-09-20T06:45:00Z,PT57S,27440,1313,26
4,n3OksLuPpVI,Comment développer une IA pour détecter une Fr...,2022-09-14T07:19:37Z,PT1M,22808,1241,18
...,...,...,...,...,...,...,...
76,wg7-roETbbM,LA RÉGRESSION LINÉAIRE (partie 1/2) - ML#3,2019-07-03T14:47:41Z,PT11M39S,326040,8137,559
77,K9z0OD22My4,APPRENTISSAGE SUPERVISÉ : LES 4 ÉTAPES - ML#2,2019-06-25T14:35:52Z,PT8M41S,297247,8438,419
78,EUD07IiviJg,FORMATION MACHINE LEARNING (2019) - ML#1,2019-06-19T15:12:15Z,PT7M32S,538865,14072,763
79,jaw5FhWx2Bk,"Comment installer ANACONDA, PYTHON, et TENSORF...",2019-06-13T18:59:31Z,PT8M45S,163923,3069,251
80,sqs8DxGhwM8,COMMENT FONCTIONNE LE MACHINE LEARNING ?,2019-04-16T06:04:01Z,PT19M18S,98945,3798,254

In [6]:
df["views"] = df["viewCount"].astype(int)
df["likes"] = df["likeCount"].astype(int)
df["comments"] = df["commentCount"].astype(int)

In [7]:
df["duration_sec"] = df["duration"].apply(
    lambda x: isodate.parse_duration(x).total_seconds()
)

In [8]:
df["published_at"] = pd.to_datetime(df["publishedAt"])

In [9]:
df_final = df[[
    "videoId",
    "title",
    "published_at",
    "duration_sec",
    "views",
    "likes",
    "comments"
]]

In [10]:
df_final

,videoId,title,published_at,duration_sec,views,likes,comments
0,SooHwC2S1iI,▶️ [REPLAY] - La carte de l'IA | Partie 2,2024-10-06 19:13:49+00:00,4670.0,29566,1171,65
1,mT6NnslbNLM,▶️ [REPLAY] - La carte de l'IA | Partie 1,2024-10-04 18:19:29+00:00,4112.0,52922,2726,192
2,SgPQe2orwAk,JE SUIS DE RETOUR ! 🚀 (et j'ai une surprise po...,2024-08-22 08:23:28+00:00,193.0,40507,3753,663
3,Je4TH0wpgQc,Comment Développer une IA capable de créer des...,2022-09-20 06:45:00+00:00,57.0,27440,1313,26
4,n3OksLuPpVI,Comment développer une IA pour détecter une Fr...,2022-09-14 07:19:37+00:00,60.0,22808,1241,18
...,...,...,...,...,...,...,...
76,wg7-roETbbM,LA RÉGRESSION LINÉAIRE (partie 1/2) - ML#3,2019-07-03 14:47:41+00:00,699.0,326040,8137,559
77,K9z0OD22My4,APPRENTISSAGE SUPERVISÉ : LES 4 ÉTAPES - ML#2,2019-06-25 14:35:52+00:00,521.0,297247,8438,419
78,EUD07IiviJg,FORMATION MACHINE LEARNING (2019) - ML#1,2019-06-19 15:12:15+00:00,452.0,538865,14072,763
79,jaw5FhWx2Bk,"Comment installer ANACONDA, PYTHON, et TENSORF...",2019-06-13 18:59:31+00:00,525.0,163923,3069,251
80,sqs8DxGhwM8,COMMENT FONCTIONNE LE MACHINE LEARNING ?,2019-04-16 06:04:01+00:00,1158.0,98945,3798,254

In [11]:
df_final.to_csv("data/youtube_clean.csv", index=False)