In [4]:
import json
import pandas as pd
import isodate
import json

In [5]:
with open("data/YT_data_2026-05-11.json", "r", encoding="utf-8") as f:
    data = json.load(f)

In [6]:
print(type(data))

<class 'list'>

In [7]:
df = pd.DataFrame(data)

In [8]:
df

,videoId,title,publishedAt,duration,viewCount,likeCount,commentCount
0,UamojHpGv18,étude de quelques instruments optiques 2 année...,2026-05-08T21:14:34Z,PT8M29S,1870,82,43
1,d8R129bNIiw,6 mai 2026,2026-05-06T15:26:48Z,PT12M45S,1597,70,42
2,EwgnAM0Qsx8,association des conducteurs ohmiques tronc commun,2026-05-04T15:09:47Z,PT28M16S,20536,749,165
3,m842y0z66Ek,la résistance électrique 1 année collège,2026-05-03T20:34:26Z,PT15M13S,3788,129,27
4,8LYsNGQvhKA,exercices le poids et la masse 3 année collège,2026-05-01T18:43:33Z,PT12M58S,2209,71,23
...,...,...,...,...,...,...,...
208,YCzE0EZvsC8,les ondes mécaniques progressives 2 bac,2024-08-16T17:07:28Z,PT25M11S,983980,19961,1501
209,Lk9sDNgtgFA,Les atomes et les ions : 3 année collège partie 2,2024-08-15T11:32:43Z,PT24M1S,340871,10126,717
210,QvR6ya398LM,les transformations lentes et rapides 2 bac,2024-08-12T16:55:02Z,PT34M16S,408271,10040,828
211,uQQYR4IOBko,mouvement de rotation d'un corps solide autour...,2024-08-03T00:08:00Z,PT19M38S,466649,10910,710
212,4zOoz46h5A4,mouvement de rotation d'un corps solide autour...,2024-07-31T00:02:44Z,PT20M46S,885783,18598,1055

In [9]:
df["views"] = df["viewCount"].astype(int)
df["likes"] = df["likeCount"].astype(int)
df["comments"] = df["commentCount"].astype(int)

In [10]:
df["duration_sec"] = df["duration"].apply(
    lambda x: isodate.parse_duration(x).total_seconds()
)

In [11]:
df["published_at"] = pd.to_datetime(df["publishedAt"])

In [12]:
df_final = df[[
    "videoId",
    "title",
    "published_at",
    "duration_sec",
    "views",
    "likes",
    "comments"
]]

In [13]:
df_final

,videoId,title,published_at,duration_sec,views,likes,comments
0,UamojHpGv18,étude de quelques instruments optiques 2 année...,2026-05-08 21:14:34+00:00,509.0,1870,82,43
1,d8R129bNIiw,6 mai 2026,2026-05-06 15:26:48+00:00,765.0,1597,70,42
2,EwgnAM0Qsx8,association des conducteurs ohmiques tronc commun,2026-05-04 15:09:47+00:00,1696.0,20536,749,165
3,m842y0z66Ek,la résistance électrique 1 année collège,2026-05-03 20:34:26+00:00,913.0,3788,129,27
4,8LYsNGQvhKA,exercices le poids et la masse 3 année collège,2026-05-01 18:43:33+00:00,778.0,2209,71,23
...,...,...,...,...,...,...,...
208,YCzE0EZvsC8,les ondes mécaniques progressives 2 bac,2024-08-16 17:07:28+00:00,1511.0,983980,19961,1501
209,Lk9sDNgtgFA,Les atomes et les ions : 3 année collège partie 2,2024-08-15 11:32:43+00:00,1441.0,340871,10126,717
210,QvR6ya398LM,les transformations lentes et rapides 2 bac,2024-08-12 16:55:02+00:00,2056.0,408271,10040,828
211,uQQYR4IOBko,mouvement de rotation d'un corps solide autour...,2024-08-03 00:08:00+00:00,1178.0,466649,10910,710
212,4zOoz46h5A4,mouvement de rotation d'un corps solide autour...,2024-07-31 00:02:44+00:00,1246.0,885783,18598,1055

In [14]:
df_final.to_csv("data/youtube_clean.csv", index=False)